version: '3'
services:
  converter_db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    container_name: audio-converter-db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  converter:
    build:
      context: .
      dockerfile: docker/converterservice/Dockerfile
    ports:
      - 3000:3000
    container_name: audio-converter-service
    environment:
      - BUCKET_NAME
  rest_interface:
    build:
      context: .
      dockerfile: docker/restinterface/Dockerfile
    ports:
      - 4000:4000
    container_name: audio-converter-rest-interface