version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    container_name: audio-converter-db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER