#!/bin/bash

new_bucket() {
  aws s3api create-bucket --bucket $1 --acl public-read-write --endpoint http://localhost:4572
}

# Assumes that localstack has been run in a docker image
# Create the buckets for testing
new_bucket source-audio 2>&1 1>/dev/null
new_bucket dest-audio 2>&1 1>/dev/null