// Code generated by protoc-gen-go. DO NOT EDIT.
// source: convert.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Encoding int32

const (
	// TODO: Add more file types
	Encoding_WAV  Encoding = 0
	Encoding_M4A  Encoding = 1
	Encoding_MP3  Encoding = 2
	Encoding_FLAC Encoding = 3
)

var Encoding_name = map[int32]string{
	0: "WAV",
	1: "M4A",
	2: "MP3",
	3: "FLAC",
}

var Encoding_value = map[string]int32{
	"WAV":  0,
	"M4A":  1,
	"MP3":  2,
	"FLAC": 3,
}

func (x Encoding) String() string {
	return proto.EnumName(Encoding_name, int32(x))
}

func (Encoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28744cb449e70622, []int{0}
}

type ConvertFileQueryResponse_Status int32

const (
	ConvertFileQueryResponse_QUEUED     ConvertFileQueryResponse_Status = 0
	ConvertFileQueryResponse_CONVERTING ConvertFileQueryResponse_Status = 1
	ConvertFileQueryResponse_COMPLETED  ConvertFileQueryResponse_Status = 2
	ConvertFileQueryResponse_FAILED     ConvertFileQueryResponse_Status = 3
)

var ConvertFileQueryResponse_Status_name = map[int32]string{
	0: "QUEUED",
	1: "CONVERTING",
	2: "COMPLETED",
	3: "FAILED",
}

var ConvertFileQueryResponse_Status_value = map[string]int32{
	"QUEUED":     0,
	"CONVERTING": 1,
	"COMPLETED":  2,
	"FAILED":     3,
}

func (x ConvertFileQueryResponse_Status) String() string {
	return proto.EnumName(ConvertFileQueryResponse_Status_name, int32(x))
}

func (ConvertFileQueryResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28744cb449e70622, []int{3, 0}
}

//
// A message that represents a request to convert
// audio at bucketSource/keySource from encodingSource
// to audio at bucketDest/keyDest in encodingDest
type ConvertFileRequest struct {
	SourceUrl            string   `protobuf:"bytes,1,opt,name=sourceUrl,proto3" json:"sourceUrl,omitempty"`
	SourceEncoding       Encoding `protobuf:"varint,6,opt,name=sourceEncoding,proto3,enum=pb.Encoding" json:"sourceEncoding,omitempty"`
	DestEncoding         Encoding `protobuf:"varint,7,opt,name=destEncoding,proto3,enum=pb.Encoding" json:"destEncoding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertFileRequest) Reset()         { *m = ConvertFileRequest{} }
func (m *ConvertFileRequest) String() string { return proto.CompactTextString(m) }
func (*ConvertFileRequest) ProtoMessage()    {}
func (*ConvertFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28744cb449e70622, []int{0}
}

func (m *ConvertFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertFileRequest.Unmarshal(m, b)
}
func (m *ConvertFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertFileRequest.Marshal(b, m, deterministic)
}
func (m *ConvertFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertFileRequest.Merge(m, src)
}
func (m *ConvertFileRequest) XXX_Size() int {
	return xxx_messageInfo_ConvertFileRequest.Size(m)
}
func (m *ConvertFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertFileRequest proto.InternalMessageInfo

func (m *ConvertFileRequest) GetSourceUrl() string {
	if m != nil {
		return m.SourceUrl
	}
	return ""
}

func (m *ConvertFileRequest) GetSourceEncoding() Encoding {
	if m != nil {
		return m.SourceEncoding
	}
	return Encoding_WAV
}

func (m *ConvertFileRequest) GetDestEncoding() Encoding {
	if m != nil {
		return m.DestEncoding
	}
	return Encoding_WAV
}

//
// A response returned from convert file indicating
// whether the request was accepted, and a unique identifier
type ConvertFileResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Accepted             bool     `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertFileResponse) Reset()         { *m = ConvertFileResponse{} }
func (m *ConvertFileResponse) String() string { return proto.CompactTextString(m) }
func (*ConvertFileResponse) ProtoMessage()    {}
func (*ConvertFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28744cb449e70622, []int{1}
}

func (m *ConvertFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertFileResponse.Unmarshal(m, b)
}
func (m *ConvertFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertFileResponse.Marshal(b, m, deterministic)
}
func (m *ConvertFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertFileResponse.Merge(m, src)
}
func (m *ConvertFileResponse) XXX_Size() int {
	return xxx_messageInfo_ConvertFileResponse.Size(m)
}
func (m *ConvertFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertFileResponse proto.InternalMessageInfo

func (m *ConvertFileResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConvertFileResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

//
// A request to the Converter service to lookup
// the status of a job
type ConvertFileQueryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertFileQueryRequest) Reset()         { *m = ConvertFileQueryRequest{} }
func (m *ConvertFileQueryRequest) String() string { return proto.CompactTextString(m) }
func (*ConvertFileQueryRequest) ProtoMessage()    {}
func (*ConvertFileQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28744cb449e70622, []int{2}
}

func (m *ConvertFileQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertFileQueryRequest.Unmarshal(m, b)
}
func (m *ConvertFileQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertFileQueryRequest.Marshal(b, m, deterministic)
}
func (m *ConvertFileQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertFileQueryRequest.Merge(m, src)
}
func (m *ConvertFileQueryRequest) XXX_Size() int {
	return xxx_messageInfo_ConvertFileQueryRequest.Size(m)
}
func (m *ConvertFileQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertFileQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertFileQueryRequest proto.InternalMessageInfo

func (m *ConvertFileQueryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

//
// A response from the Converter service that contains
// the id of the job, and its current status
type ConvertFileQueryResponse struct {
	Id                   string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               ConvertFileQueryResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=pb.ConvertFileQueryResponse_Status" json:"status,omitempty"`
	ErrMsg               string                          `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ConvertFileQueryResponse) Reset()         { *m = ConvertFileQueryResponse{} }
func (m *ConvertFileQueryResponse) String() string { return proto.CompactTextString(m) }
func (*ConvertFileQueryResponse) ProtoMessage()    {}
func (*ConvertFileQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28744cb449e70622, []int{3}
}

func (m *ConvertFileQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertFileQueryResponse.Unmarshal(m, b)
}
func (m *ConvertFileQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertFileQueryResponse.Marshal(b, m, deterministic)
}
func (m *ConvertFileQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertFileQueryResponse.Merge(m, src)
}
func (m *ConvertFileQueryResponse) XXX_Size() int {
	return xxx_messageInfo_ConvertFileQueryResponse.Size(m)
}
func (m *ConvertFileQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertFileQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertFileQueryResponse proto.InternalMessageInfo

func (m *ConvertFileQueryResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConvertFileQueryResponse) GetStatus() ConvertFileQueryResponse_Status {
	if m != nil {
		return m.Status
	}
	return ConvertFileQueryResponse_QUEUED
}

func (m *ConvertFileQueryResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

//
// A request to convert a buffer of audio data
// from sourceEncoding to destEncoding
type ConvertStreamRequest struct {
	Buff                 []byte   `protobuf:"bytes,1,opt,name=buff,proto3" json:"buff,omitempty"`
	SourceEncoding       Encoding `protobuf:"varint,2,opt,name=sourceEncoding,proto3,enum=pb.Encoding" json:"sourceEncoding,omitempty"`
	DestEncoding         Encoding `protobuf:"varint,3,opt,name=destEncoding,proto3,enum=pb.Encoding" json:"destEncoding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertStreamRequest) Reset()         { *m = ConvertStreamRequest{} }
func (m *ConvertStreamRequest) String() string { return proto.CompactTextString(m) }
func (*ConvertStreamRequest) ProtoMessage()    {}
func (*ConvertStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28744cb449e70622, []int{4}
}

func (m *ConvertStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertStreamRequest.Unmarshal(m, b)
}
func (m *ConvertStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertStreamRequest.Marshal(b, m, deterministic)
}
func (m *ConvertStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertStreamRequest.Merge(m, src)
}
func (m *ConvertStreamRequest) XXX_Size() int {
	return xxx_messageInfo_ConvertStreamRequest.Size(m)
}
func (m *ConvertStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertStreamRequest proto.InternalMessageInfo

func (m *ConvertStreamRequest) GetBuff() []byte {
	if m != nil {
		return m.Buff
	}
	return nil
}

func (m *ConvertStreamRequest) GetSourceEncoding() Encoding {
	if m != nil {
		return m.SourceEncoding
	}
	return Encoding_WAV
}

func (m *ConvertStreamRequest) GetDestEncoding() Encoding {
	if m != nil {
		return m.DestEncoding
	}
	return Encoding_WAV
}

//
// A convert stream response containing the converted buffer
type ConvertStreamResponse struct {
	Buff                 []byte   `protobuf:"bytes,1,opt,name=buff,proto3" json:"buff,omitempty"`
	Encoding             Encoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=pb.Encoding" json:"encoding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertStreamResponse) Reset()         { *m = ConvertStreamResponse{} }
func (m *ConvertStreamResponse) String() string { return proto.CompactTextString(m) }
func (*ConvertStreamResponse) ProtoMessage()    {}
func (*ConvertStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28744cb449e70622, []int{5}
}

func (m *ConvertStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertStreamResponse.Unmarshal(m, b)
}
func (m *ConvertStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertStreamResponse.Marshal(b, m, deterministic)
}
func (m *ConvertStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertStreamResponse.Merge(m, src)
}
func (m *ConvertStreamResponse) XXX_Size() int {
	return xxx_messageInfo_ConvertStreamResponse.Size(m)
}
func (m *ConvertStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertStreamResponse proto.InternalMessageInfo

func (m *ConvertStreamResponse) GetBuff() []byte {
	if m != nil {
		return m.Buff
	}
	return nil
}

func (m *ConvertStreamResponse) GetEncoding() Encoding {
	if m != nil {
		return m.Encoding
	}
	return Encoding_WAV
}

func init() {
	proto.RegisterEnum("pb.Encoding", Encoding_name, Encoding_value)
	proto.RegisterEnum("pb.ConvertFileQueryResponse_Status", ConvertFileQueryResponse_Status_name, ConvertFileQueryResponse_Status_value)
	proto.RegisterType((*ConvertFileRequest)(nil), "pb.ConvertFileRequest")
	proto.RegisterType((*ConvertFileResponse)(nil), "pb.ConvertFileResponse")
	proto.RegisterType((*ConvertFileQueryRequest)(nil), "pb.ConvertFileQueryRequest")
	proto.RegisterType((*ConvertFileQueryResponse)(nil), "pb.ConvertFileQueryResponse")
	proto.RegisterType((*ConvertStreamRequest)(nil), "pb.ConvertStreamRequest")
	proto.RegisterType((*ConvertStreamResponse)(nil), "pb.ConvertStreamResponse")
}

func init() {
	proto.RegisterFile("convert.proto", fileDescriptor_28744cb449e70622)
}

var fileDescriptor_28744cb449e70622 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xee, 0xda, 0x95, 0xeb, 0x0c, 0x89, 0xb5, 0x1a, 0xa0, 0x35, 0xa1, 0x87, 0xc8, 0x5c, 0x02,
	0x87, 0x80, 0xd2, 0xde, 0x90, 0x40, 0x56, 0xe2, 0xa0, 0x4a, 0x49, 0x7f, 0x9c, 0xa6, 0x9c, 0x13,
	0x7b, 0x5a, 0x59, 0x2a, 0xb1, 0x59, 0xaf, 0x2b, 0xf1, 0x1a, 0x1c, 0x79, 0x1a, 0xde, 0x86, 0xd7,
	0x40, 0xb1, 0x37, 0x26, 0x71, 0xdd, 0x22, 0xf5, 0x36, 0x33, 0xfb, 0xcd, 0xb7, 0xdf, 0xcc, 0xb7,
	0x0b, 0xad, 0x20, 0x5e, 0xde, 0x91, 0x90, 0xbd, 0x44, 0xc4, 0x32, 0x46, 0x2d, 0x59, 0x38, 0xbf,
	0x18, 0xe0, 0xa0, 0xa8, 0x8e, 0xa2, 0x5b, 0xf2, 0xe9, 0x7b, 0x46, 0xa9, 0xc4, 0x43, 0x68, 0xa4,
	0x71, 0x26, 0x02, 0x9a, 0x89, 0x5b, 0x9b, 0x75, 0x58, 0xb7, 0xe1, 0xff, 0x2b, 0xe0, 0x31, 0x58,
	0x45, 0xe2, 0x2d, 0x83, 0x38, 0x8c, 0x96, 0x37, 0xb6, 0xd1, 0x61, 0x5d, 0xab, 0xdf, 0xec, 0x25,
	0x8b, 0xde, 0xba, 0xe6, 0x57, 0x30, 0xf8, 0x01, 0x9a, 0x21, 0xa5, 0xb2, 0xec, 0xd9, 0xab, 0xe9,
	0xd9, 0x42, 0x38, 0x2e, 0x3c, 0xdf, 0xd2, 0x96, 0x26, 0xf1, 0x32, 0x25, 0xb4, 0x40, 0x8b, 0x42,
	0xa5, 0x4a, 0x8b, 0x42, 0x6c, 0x83, 0x39, 0x0f, 0x02, 0x4a, 0x24, 0x85, 0xb6, 0xd6, 0x61, 0x5d,
	0xd3, 0x2f, 0x73, 0xe7, 0x2d, 0x1c, 0x6c, 0x50, 0x5c, 0x64, 0x24, 0x7e, 0xac, 0x67, 0xac, 0xd0,
	0x38, 0xbf, 0x19, 0xd8, 0xf7, 0xb1, 0x0f, 0xdc, 0xf9, 0x11, 0x8c, 0x54, 0xce, 0x65, 0x96, 0xe6,
	0x37, 0x5a, 0xfd, 0x37, 0xab, 0x31, 0x1e, 0xea, 0xee, 0x4d, 0x73, 0xa8, 0xaf, 0x5a, 0x70, 0x1f,
	0x0c, 0x12, 0x62, 0x92, 0xde, 0xd8, 0x7a, 0x4e, 0xa8, 0x32, 0xe7, 0x33, 0x18, 0x05, 0x12, 0x01,
	0x8c, 0x8b, 0x99, 0x37, 0xf3, 0x86, 0x7c, 0x07, 0x2d, 0x80, 0xc1, 0xd9, 0xe9, 0x95, 0xe7, 0x5f,
	0x9e, 0x9c, 0x7e, 0xe1, 0x0c, 0x5b, 0xd0, 0x18, 0x9c, 0x4d, 0xce, 0xc7, 0xde, 0xa5, 0x37, 0xe4,
	0xda, 0x0a, 0x3a, 0x72, 0x4f, 0xc6, 0xde, 0x90, 0xeb, 0xce, 0x4f, 0x06, 0x2f, 0x94, 0x88, 0xa9,
	0x14, 0x34, 0xff, 0xb6, 0x9e, 0x15, 0x61, 0x77, 0x91, 0x5d, 0x5f, 0xe7, 0x03, 0x34, 0xfd, 0x3c,
	0xae, 0x71, 0x51, 0x7b, 0x82, 0x8b, 0xfa, 0x7f, 0x5d, 0x9c, 0xc1, 0xcb, 0x8a, 0x26, 0xb5, 0xd3,
	0x3a, 0x51, 0x5d, 0x30, 0xe9, 0x31, 0x39, 0xe5, 0xe9, 0xbb, 0xf7, 0x60, 0x96, 0xa2, 0xf6, 0x40,
	0xff, 0xea, 0x5e, 0xf1, 0x9d, 0x55, 0x30, 0x39, 0x76, 0x39, 0xcb, 0x83, 0xf3, 0x23, 0xae, 0xa1,
	0x09, 0xbb, 0xa3, 0xb1, 0x3b, 0xe0, 0x7a, 0xff, 0x0f, 0x03, 0xae, 0x84, 0x90, 0x98, 0x92, 0xb8,
	0x8b, 0x02, 0xc2, 0x4f, 0xf0, 0x6c, 0xc3, 0x35, 0xdc, 0xaf, 0xd8, 0xa8, 0xf6, 0xd7, 0x3e, 0xb8,
	0x57, 0x57, 0x33, 0x4c, 0x4a, 0xce, 0xd2, 0x75, 0x7c, 0x5d, 0xff, 0x16, 0x0a, 0xa6, 0xc3, 0xc7,
	0x1e, 0x0a, 0x0e, 0xa1, 0xb5, 0xb5, 0x2b, 0xb4, 0x37, 0xe0, 0x5b, 0x96, 0xb6, 0x5f, 0xd5, 0x9c,
	0x14, 0x2c, 0x0b, 0x23, 0xff, 0xdf, 0x47, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x92, 0xbf,
	0xd6, 0xf0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ConverterServiceClient is the client API for ConverterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConverterServiceClient interface {
	//
	// Create a file encoding conversion job from S3
	ConvertFile(ctx context.Context, in *ConvertFileRequest, opts ...grpc.CallOption) (*ConvertFileResponse, error)
	//
	// Lookup the status of a job
	ConvertFileQuery(ctx context.Context, in *ConvertFileQueryRequest, opts ...grpc.CallOption) (*ConvertFileQueryResponse, error)
	//
	// Stream an audio file to the conversion service for real-time conversion
	ConvertStream(ctx context.Context, in *ConvertStreamRequest, opts ...grpc.CallOption) (*ConvertStreamResponse, error)
}

type converterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConverterServiceClient(cc grpc.ClientConnInterface) ConverterServiceClient {
	return &converterServiceClient{cc}
}

func (c *converterServiceClient) ConvertFile(ctx context.Context, in *ConvertFileRequest, opts ...grpc.CallOption) (*ConvertFileResponse, error) {
	out := new(ConvertFileResponse)
	err := c.cc.Invoke(ctx, "/pb.ConverterService/ConvertFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *converterServiceClient) ConvertFileQuery(ctx context.Context, in *ConvertFileQueryRequest, opts ...grpc.CallOption) (*ConvertFileQueryResponse, error) {
	out := new(ConvertFileQueryResponse)
	err := c.cc.Invoke(ctx, "/pb.ConverterService/ConvertFileQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *converterServiceClient) ConvertStream(ctx context.Context, in *ConvertStreamRequest, opts ...grpc.CallOption) (*ConvertStreamResponse, error) {
	out := new(ConvertStreamResponse)
	err := c.cc.Invoke(ctx, "/pb.ConverterService/ConvertStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConverterServiceServer is the server API for ConverterService service.
type ConverterServiceServer interface {
	//
	// Create a file encoding conversion job from S3
	ConvertFile(context.Context, *ConvertFileRequest) (*ConvertFileResponse, error)
	//
	// Lookup the status of a job
	ConvertFileQuery(context.Context, *ConvertFileQueryRequest) (*ConvertFileQueryResponse, error)
	//
	// Stream an audio file to the conversion service for real-time conversion
	ConvertStream(context.Context, *ConvertStreamRequest) (*ConvertStreamResponse, error)
}

// UnimplementedConverterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConverterServiceServer struct {
}

func (*UnimplementedConverterServiceServer) ConvertFile(ctx context.Context, req *ConvertFileRequest) (*ConvertFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertFile not implemented")
}
func (*UnimplementedConverterServiceServer) ConvertFileQuery(ctx context.Context, req *ConvertFileQueryRequest) (*ConvertFileQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertFileQuery not implemented")
}
func (*UnimplementedConverterServiceServer) ConvertStream(ctx context.Context, req *ConvertStreamRequest) (*ConvertStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertStream not implemented")
}

func RegisterConverterServiceServer(s *grpc.Server, srv ConverterServiceServer) {
	s.RegisterService(&_ConverterService_serviceDesc, srv)
}

func _ConverterService_ConvertFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConverterServiceServer).ConvertFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ConverterService/ConvertFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConverterServiceServer).ConvertFile(ctx, req.(*ConvertFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConverterService_ConvertFileQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertFileQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConverterServiceServer).ConvertFileQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ConverterService/ConvertFileQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConverterServiceServer).ConvertFileQuery(ctx, req.(*ConvertFileQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConverterService_ConvertStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConverterServiceServer).ConvertStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ConverterService/ConvertStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConverterServiceServer).ConvertStream(ctx, req.(*ConvertStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConverterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ConverterService",
	HandlerType: (*ConverterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertFile",
			Handler:    _ConverterService_ConvertFile_Handler,
		},
		{
			MethodName: "ConvertFileQuery",
			Handler:    _ConverterService_ConvertFileQuery_Handler,
		},
		{
			MethodName: "ConvertStream",
			Handler:    _ConverterService_ConvertStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "convert.proto",
}
